appName: frontend-service
appImage: gcr.io/google-samples/microservices-demo/frontend
appVersion: v0.8.0
appReplicas: 2
containerPort: 8080
containerEnvVars:
- name: PORT
  value: "8080"
- name: PRODUCT_CATALOG_SERVICE_ADDR
  value: product-catalog-service:7000
- name: CURRENCY_SERVICE_ADDR
  value: currency-service:9000
- name: AD_SERVICE_ADDR
  value: ad-service:11000
- name: CART_SERVICE_ADDR
  value: cart-service:12000
- name: CHECKOUT_SERVICE_ADDR
  value: checkout-service:14000
- name: RECOMMENDATION_SERVICE_ADDR
  value: recommendation-service:6000
- name: SHIPPING_SERVICE_ADDR
  value: shipping-service:10000
livenessProbe:
  httpGet:
    path: /_healthz
    port: 8080
    httpHeaders:
      - name: Cookie
        value: shop_session-id=x-liveness-probe
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /_healthz
    port: 8080
    httpHeaders:
      - name: Cookie
        value: shop_session-id=x-readiness-probe
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 3
resources:
  requests:
    cpu: "100m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
serviceType: LoadBalancer
servicePort: 9090
nodePort: 30090
