def gv

pipeline {
    agent any
    tools {
        nodejs 'node-22'
    }

    stages {
        stage('init') {
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv = load 'pipeline.groovy'
                    }
                    echo "branch name is ${env.BRANCH_NAME}"
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv.RunTests()
                    }
                }
            }
        }
        stage('Increment backend version') {
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv.IncrementBackendVersion()
                    }
                }
            }
        }
        stage('Build backend image') {
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv.BuildBackendImage()
                    }
                }
            }
        }
        stage('Increment frontend version') {
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv.IncrementFrontendVersion()
                    }
                }
            }
        }
        stage('Build frontend image') {
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv.BuildFrontendImage()
                    }
                }
            }
        }
        stage('Deploy to server') {
            when {
                expression {
                    return env.BRANCH_NAME == 'main'
                }
            }
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv.DeployOnServer()
                    }
                }
            }
        }
        stage('Version bump') {
            steps {
                script {
                    dir('JenkinsCompletePipeline') {
                        gv.VersionBump()
                    }
                }
            }
        }
    }

}
