
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRVkvbDhlMnBmZjh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01EY3dNak14TXpoYUZ3MHpOakEzTURRd01qTTJNemhhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURPSHorWWNmbEV2KzAyWVpER3lPN0pqUWNuSG81bTR3Z0FyQm1jK2FiRWtuUzdRWFBIaGVJK1RnVWoKTjU1WUI2MlJDbWRMd0pSeUluZTlUdkVGckZJdzR6ZlZHV3phVG1Ib3cvYUtDYXBpK3VUSDNNV3FNa3dvdzlvWgpxcU5JS1FycGJGYzA2RlhZdWQzM1FlMmtaTjQ4UmNFd2NaNjArWTA0Tm9WTFBXMlhDUEIxRjRlMFNhUjNtSHJkCmZpdjlBWUVzWE9Ld1hjM3c0a3N2S0x2bjQ1MUhLUG9KbVFURkEvZFpkTExiL2k5NjZkd3NRaFdxMXZ1ZFBKMGMKcnVuK2VtWEVvNGlrWnNQdXRneGpxUHpKRUt4N1V1cGIxUHZmUzRPTC8zMG00aHVjZzVqWHNMY3dMVElqWVNzWAphUFkwUmdJSDkvSG5zaTduOXpTRHpNMVNnOE1UQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUeDFNWmlSRk13dkJTQWdyMUQveFI2OW5yWkJqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ3I4dzhGd0lxSwpzRjIzdWFSSUZDeUtsWlpJVVhuN1ozd2Y1U0dSMlg1Z2l5akljN04xTU4rRmF0K1NGOUNoR2lJVDVwZmN3WWE5CmNGNktsb0kvMkZIU3JWVU5ZQ2FRSWM2SmEzN2VZQzJZWjRybVViQTMweWJ2V2laQjhUZzhsWEVuSE16OUQwZWMKMXZ6aWdCUCtoOURLdkhhNTRoSkxKV1piTGlOUDRFMGJ2ZjhZMjVQZHF6TkRvc2c2QnhKZE9XYkpRd1dtMEtrcQozciswQzBQbk9UNEVtc3dJaE1iN25hVFZ6alRPbHMwSktJY3JmMzlEc0FwbGgwRldLUzRHUmdjekZZYkRiVUUwCkRLNG53MW1WYjB6M1d3TGtGTXBWMkZPUk05V3Z2TFc3S0t3eWc1Q29ISEJaVFp1QUhaWTdKTUExMFhrMWJmTjYKTlBkSkcybG91dXJICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://9dd56f15-8bdf-410d-a0d5-6897622fb4ae.ap-west-1-gw.linodelke.net:443
  name: lke627140

users:
- name: lke627140-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjVyWjc0ZGxDNnNRQ0RjbnJjSFphTE5hZVF3R0UyLUNiR2JKTElmRHlZSDQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tcXpmemwiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNmVlMDE2ZWUtZjcyYy00MzNiLWE0MmUtZGQwMDAxOTg3MzU1Iiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.hZQ6nQL1Qos7lr8AgNb98WdSy7iyxFNJRhbx2uJ-vLcvnI_H-dbWc0GcIM1QOBIb3646OV-V1tzCCEvt6Ykt36VBBXcYnPYyAotfHjlPsn5AjRp63jQzRX-NdJMRpdBW4Lc9v3DsefPBRO2pqN8SJdPut-UBE9UI5asao-VYHac8yATG1QpHBiX_u1uhj2GrmOvGlT3UL8u0NmRAr8y3wzmFnH5IUlEKy5KDkc2u-0lob01cvID3SpUDWJ0tX1Z4vwj4SbsPN6f-kNfRU_qBLoYEdPsT3C-F2s42sryTGsjSxsuCQlVOc7QB8jYGUAhFNYNFtgx3zIi2rrxscjQigQ

contexts:
- context:
    cluster: lke627140
    namespace: default
    user: lke627140-admin
  name: lke627140-ctx

current-context: lke627140-ctx
