--- 

- name: Server Update and install Docker
  hosts: linode
  become: yes 
  tasks:
    - name : update apt and cache 
      apt: 
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    
    - name: install Docker
      apt: 
         name: docker.io
         state: present

- name: Start docker and add user to the docker group
  hosts: linode
  become: yes
  tasks:
    - name: run docker 
      systemd:
       name: docker
       state: started
       enabled: yes

    - name: create a docker group
      group: 
       name: docker
       state: present

    - name: create jenkins user 
      user:
       name: jenkins_user
       groups: docker
       append: yes
       state: present

    - name: reconnect to server to apply group changes
      meta: reset_connection

- name: Get Docker socket group ID
  hosts: linode
  become: yes
  tasks:

    - name: Get Docker socket group ID
      ansible.builtin.stat:
        path: /var/run/docker.sock
      register: docker_socket

    - name: Show Docker socket group ID
      ansible.builtin.debug:
        msg: "Docker socket GID: {{ docker_socket.stat.gid }}"

- name: pull jenkins image in linode server and start 
  hosts: linode
  become_user: jenkins_user
  tasks:
   - name: pull jenkins image
     community.docker.docker_image:
        name: jenkins/jenkins
        tag: lts-jdk21
        source: pull
   - name: Create Jenkins volume
     community.docker.docker_volume:
        name: jenkins_home
   - name: Run Jenkins container
     community.docker.docker_container:
        name: jenkins
        image: jenkins/jenkins:lts-jdk21
        state: started
        restart_policy: unless-stopped
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock

        groups:
          - "{{ docker_socket.stat.gid }}"

- name: Install DevOps tools inside Jenkins container
  hosts: linode
  become: yes

  tasks:
    - name: Update apt inside Jenkins container
      community.docker.docker_container_exec:
        container: jenkins
        command: apt-get update
        user: root

    - name: Install Docker CLI, Ansible and required packages
      community.docker.docker_container_exec:
        container: jenkins
        command: >
          apt-get install -y
          docker.io
          ansible
          wget
          unzip
        user: root

    - name: Download Terraform
      community.docker.docker_container_exec:
        container: jenkins
        command: >
          wget -q
          https://releases.hashicorp.com/terraform/1.13.1/terraform_1.13.1_linux_amd64.zip
          -O /tmp/terraform.zip
        user: root

    - name: Extract Terraform
      community.docker.docker_container_exec:
        container: jenkins
        command: >
          unzip -o /tmp/terraform.zip -d /usr/local/bin/
        user: root

    - name: Verify Terraform
      community.docker.docker_container_exec:
        container: jenkins
        command: terraform --version
        user: root

    - name: Verify Ansible
      community.docker.docker_container_exec:
        container: jenkins
        command: ansible --version
        user: root

    - name: Verify Docker
      community.docker.docker_container_exec:
        container: jenkins
        command: docker --version
        user: root
      



  