def gv

pipeline {

    agent any

    tools {
        nodejs 'nodejs-22'
    }

    stages {

        stage('Init') {
            steps {
                script {
                     dir('completeProject1') {
                    gv = load 'pipeline.groovy'
                     }
                    echo "Branch name is ${env.BRANCH_NAME}"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('completeProject1') {
                    gv.RunTests()
                    }
                }
            }
        }

        stage('Main Pipeline') {

            when {
                branch 'practice-project-1'
            }

            stages {

                stage('Creating infra for the application') {
                    steps {
                        script {
                            dir('completeProject1') {
                            gv.CreateInfrastructure()
                        }
                        }
                    }
                }

                stage('Increment backend version') {
                    steps {
                        script {
                            dir('completeProject1') {
                            gv.IncrementBackendVersion()
                        }
                        }
                    }
                }

                stage('Build backend image') {
                    steps {
                        script {
                            dir('completeProject1') {
                            gv.BuildBackendImage()
                        }
                        }
                    }
                }

                stage('Increment frontend version') {
                    steps {
                        script {
                            dir('completeProject1') {
                            gv.IncrementFrontendVersion()
                        }
                        }
                    }
                }

                stage('Build frontend image') {
                    steps {
                        script {
                            dir('completeProject1') {
                            gv.BuildFrontendImage()
                        }
                        }
                    }
                }

                stage('Deploy to server using Ansible') {
                    steps {
                        script {
                            dir('completeProject1') {
                            gv.DeployOnServer()
                        }
                        }
                    }
                }

                stage('Version bump') {
                    steps {
                        script {
                            dir('completeProject1') {
                            gv.VersionBump()
                        }
                        }
                    }
                }
            }
        }
    }
}