
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJRUw1bkZXdGhrRFl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01EVXhNalV6TXpsYUZ3MHpOakEzTURJeE1qVTRNemxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURwOU9vU0xiN0hXY1BBS2RVK1c1TEMyOG5iRjRVTFlEMUxnbE9YVjdaWWtqZ21tYW5veUxUK1FWeFQKOGtYL25SZUtjVnluU01PeUdCczJYSTQ3UUNYTHdpaUNualZGYWFjRk9WcXVnWWFJUVNHS1B1L21zdFRXN1gxWApkSERhYlp5QzYxY1cxTVRrY3FsMVFsSlRsd3ZYWU12bnJLaFF2dlN2bFBWR1dFQkI5TzFYdkNXZ2tFRndoejhoCnhGenBxaC9rNGNRS09TaFBRdUlOL3NLOTQ5RExJY0hCT3RoVVVtZmc0MlBBRVNPbkY1aGR4SXpELzBTMThoVU0KRmRzaHU3aklzYTl5bk5HOUFSQjBVQ1VLcUVzWGY4VGJQTm5HYmNURVNLaXhkQkxiRXFRMkpIV2xZbklubDVlSgpvczFVWlNNWmVTUmtTQVpvVzl0SmxHLzFxbld0QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTZk5YblNGQzNQekloRDViaU1UdE94NUpqSnFEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQmtnU1JVYVVkcwp2UStTU2ovejZzWHJxVDVPQnFqYkNWR2FTWHJVazNSa0JDbHZrTDdneDAyWlZ1amNEVUloWUcvL0ZXd2lxVmRpCmxrTW1UR0FZTW9jaDJWNW1lMFRPdGpNV0NnMWYrN2xhcTFIQWFXZVVzZ1VoMHhOZ1FXWW5jZ1NJT0orQkRqb3AKMXVnMEwwY0lhbWZZQVZOL1dza3FiNTJzSHZROFVUaUV1anJ1ZE9CQmlLUE1ZbmZBZ3F2WU5CeHdzelp5aEQ4YQpMalVKVnBxQUcvOWx5WjFyS08rOHlrTlRVMjFQZVlBbGEvaDNEUHkrYmRwWG9FZ01xSUlISm9YSkZrWm1TSjJjCmxnZTdvaXNNdnBWWW91cG1ROHFNV043TEphZnExL1hrZ2xCQ1c4Y1VOa0MrZTR2WVp3ZWkrRnFQeEJQK1NGK3gKRDBtSUpWMXFOaVRTCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c831ee71-bc90-4f17-bdeb-95c501699748.ap-west-1-gw.linodelke.net:443
  name: lke626297

users:
- name: lke626297-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Il81WF9iWktqWk1FR1ZrdTZlaGFvWUE5Vjg3X2c0ZGJZaEZkZ05naTVRLTQifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4td3Rya2oiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiN2QxZWRmYmYtNzM1Mi00YThiLWIxZGItNmVmM2UyYTI2ZDRkIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.bj_bOBYZXqAYl_uAcfxuF72ImQMXMWgW8x9InYOGhA06xc098H9uumz0kynC-LU9WJRzDXJRcZ1hW7u-QhC0YJocHn7dMX1JQuejgOhZaMXpMNoBO6F-9_sx569WN1yeRBdP0Rzkt_BUiw5TPLIR6e3JkL4AvSdeeCHHHN7ChVojcY-UJ5QUna467NmFE1z5y6Fez2GMv1W7SKyXvLx-UPgTthSK_Tgfed2kctlW0JaG2-uH7YyN-lGJK6e1RClryzlsCbaIhFCMwb2z8IdDa6j4Jpfz8S3C5CGbP5R4l4TcbAXMkrBvyQ7JKmRDZvzQ84L3IAT_IlC7f_pwJR60vA

contexts:
- context:
    cluster: lke626297
    namespace: default
    user: lke626297-admin
  name: lke626297-ctx

current-context: lke626297-ctx
