
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSlVxS0x2WUZCTmN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBM01EUXhNRE0xTURCYUZ3MHpOakEzTURFeE1EUXdNREJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURWSUVlUWk0WDAvaTJ5d2JaMDBSNVFvZThBQm5nbUx6SUlWbmJHNjYyM3FPdC9ET2t2NndlL0xRRjgKeHBDUThGYXY4cHc0REJsYXVrc3dHMWpsNnlvSUVpZHlyWFlOdFFEUlc2T2I5eEtyWGkxbytqK1gzd1VCL0dQagpHUW5SUjh2OGpBZ2phTVJJSVBUK0VONk54ZTc5TW84dmY1T3VlSEYzdXVOZ1BUZmVpakp6Tlk5VVhLS1JGVTZEClZzeG9manE0c3UvdVZnZU43TzhxMHdRZEUyV0hrN2tBUjBpcnMvclZzMmdJQStyaUVCdlhUc1h6WWZIMVNYZlIKMWFTcC80cGxrb3NLMExqajd0Nk1yMDN5R251Uzc4VHpDNlVFZ09yczJsQ1VVUFZZRFU0SVdKTWRhMjd2NHVZZworbE82QXB4NHJJUUk2b0llWDExaGdxb1FYWjgvQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRUzZHNi9JMHBMMWR1SkJqNEQvZW9uZWhKSG5qQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRREdZSnBrL3QrUwpWNU0wSHFtbUI1OEVzenUzYTdPRUJQN2Y4VWZVQ2FxSHd1dUp1dHV0L1ZtWE5uZzVsTXFOdkN2UmJ2Y00xK0piCjlzOGJxN1ZFc25IbENCM01WbUxhNXREdjZzdXZuWWNNazdVR2ZKblZHMTBQaXdka1NqZThPcnFlNk5PRHJjN0MKQTJ6alBEcmhoS1RFaGRmWXoxNmJoenFaSVlkMUVmMzdUWldpM3h5WVZlclpxdS9hY0hKTmo4d25Tc0hTUVVtQgpVWlBxcDV6S1lCT2QyVkdqNmpZNTFlSjk2R0xuc0ExWjBwc0VOM3AyN0ZsRnowRzBsYjJSUFkvdHNZd3lsc1hwCmt2RmF4WjhhZWdzbHRGcUsvZmxHK2Y4cXExRDhRSU91bTlNVVZCZUN5V1JtVy9ldlBZb0tFdFpOYm4rNWVIRjAKQ08xd2VLWjladkwwCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c60ed70c-b76b-47e1-a087-e6e27ac06ad5.ap-west-1-gw.linodelke.net:443
  name: lke626090

users:
- name: lke626090-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjRlbmV4QkhySFNxQW05MlM3SUh1c1FmZ0FHTzBJUVUxVDkyMWJrZG1NUHMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbmQ3d3giLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzIxNDg3MzMtODIzNS00MWRlLTk2YzUtNjBjOWE5NDhjMzYxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.FFRfmha9tWXBp7zgmPCSYnuuSPjo-qcBp4Vm503GhSK0xw0zRsBmjEs-NUC-pfE7zVXkxn5JBy_2fDB06fIPEnE347bZlE5pWkL6o9I__IIZu63D9N7d33ZO-fkIuRhlT-EFuD86G95NdcS5P2xJ2bi66b_WnLIDkYMGCqJZ1kCz-402dm3w4TFA-6gY_FY6LqbSFLzLgo1d4St68JLptSBCrSmqA5Rdg09ARwmtreRhQFv2XaG2rBErnLGLZl9B8j1uSNHx5shgHyLV1RqaJPeS2ylqrHg3gF_Q5ZxwT3Yf0yAJqV6wZbfP-9CBx68vg0D8fL-Un33B8W894S4M5w

contexts:
- context:
    cluster: lke626090
    namespace: default
    user: lke626090-admin
  name: lke626090-ctx

current-context: lke626090-ctx
